"""test_model_cards.py — the model cards must agree with the artifacts.

A model card is a governance document: it is the thing a reviewer reads
INSTEAD of the code. That makes a stale one worse than none, and this project
already knows the failure — CLAUDE.md §17.11 records a retracted claim
surviving simultaneously in the README, both dashboard pages, the API, a
committed .docx and a JSON field the API re-serves, because each copy was
edited by hand and nothing could tell they had drifted apart.

So the cards are generated (`scripts/build_model_cards.py`) and these tests
assert the generated text still matches `data/gold/`. They mirror
`tests/test_run_dashboard_data.py`, including its source-inspection test
forbidding hardcoded result literals.

SKIP POLICY matches tests/test_artifact_consistency.py: skip when the
artifacts or the cards are absent, so a fresh clone without `dvc pull` stays
green; assert hard whenever they are present.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
GOLD = ROOT / "data" / "gold"
DOCS = ROOT / "docs"
GENERATOR = ROOT / "scripts" / "build_model_cards.py"

PRIMARY_CARD = DOCS / "MODEL_CARD_REGIME_CONDITIONAL.md"
CHALLENGER_CARDS = {
    "rf_signal_tuned": DOCS / "MODEL_CARD_RF_CHALLENGER.md",
    "xgb_signal_tuned": DOCS / "MODEL_CARD_XGB_CHALLENGER.md",
}


def _artifact(name: str) -> dict:
    path = GOLD / name
    if not path.is_file():
        pytest.skip(f"{name} not present — run the pipeline or `dvc pull` first.")
    return json.loads(path.read_text(encoding="utf-8"))


def _card(path: Path) -> str:
    if not path.is_file():
        pytest.skip(f"{path.name} not built — run scripts/build_model_cards.py.")
    return path.read_text(encoding="utf-8")


def _flat(path: Path) -> str:
    """Card text with newlines and blockquote markers collapsed to spaces.

    Phrase assertions must survive line wrapping: the statements below are
    governance requirements, not formatting requirements, and a reflow should
    not be able to silently drop one.
    """
    return re.sub(r"\s+", " ", _card(path).replace("\n>", " "))


@pytest.fixture(scope="module")
def paired() -> dict:
    return _artifact("paired_comparison_results.json")


class TestEveryCardExists:
    def test_all_three_cards_are_present(self):
        missing = [p.name for p in [PRIMARY_CARD, *CHALLENGER_CARDS.values()]
                   if not p.is_file()]
        if missing:
            pytest.skip(f"cards not built: {missing}")

    def test_cards_declare_they_are_generated(self):
        for path in [PRIMARY_CARD, *CHALLENGER_CARDS.values()]:
            assert "GENERATED by scripts/build_model_cards.py" in _card(path), (
                f"{path.name} lost its generated-file marker; a reader could "
                f"reasonably edit it by hand and see the change silently reverted."
            )


class TestCardsMatchThePairedArtifact:
    """Numbers in the cards are read from Gold, not typed. Prove it still holds."""

    def test_every_comparison_appears_in_the_relevant_challenger_card(self, paired):
        for candidate, path in CHALLENGER_CARDS.items():
            card = _card(path)
            rows = [c for c in paired["comparisons"] if c["candidate"] == candidate]
            assert rows, f"artifact holds no comparison for {candidate}"
            for comparison in rows:
                delta = f"{comparison['sharpe_diff']:+.3f}"
                p_value = f"{comparison['p_value_no_outperformance']:.3f}"
                assert delta in card, (
                    f"{path.name}: Δ={delta} for {comparison['universe']} vs "
                    f"{comparison['benchmark']} is absent. Re-run "
                    f"scripts/build_model_cards.py."
                )
                assert p_value in card, f"{path.name}: p={p_value} is absent."

    def test_primary_card_carries_all_comparisons(self, paired):
        card = _card(PRIMARY_CARD)
        for comparison in paired["comparisons"]:
            assert f"{comparison['sharpe_diff']:+.3f}" in card

    def test_the_established_count_is_recomputed_not_asserted(self, paired):
        """The headline sentence must follow the data if the data changes."""
        established = [
            c for c in paired["comparisons"]
            if c["sharpe_diff_ci"][0] > 0 and c["p_value_no_outperformance"] < 0.05
        ]
        card = _card(PRIMARY_CARD)
        assert f"**{len(established)}** established" in card, (
            f"The primary card must state the recomputed count of comparisons "
            f"establishing outperformance ({len(established)}), not a fixed word."
        )


class TestGovernanceStatementsArePresent:
    """The claims this project may NOT make, and the ones it must."""

    def test_no_card_claims_significance_or_equivalence(self):
        # The §5.2 reframing, made executable. Both over-claims are banned:
        # "significant" in favour, "indistinguishable"/"equivalent" against.
        banned = ("statistically significant", "statistically indistinguishable",
                  "proves superiority", "outperforms the benchmark")
        for path in [PRIMARY_CARD, *CHALLENGER_CARDS.values()]:
            lowered = _card(path).lower()
            for phrase in banned:
                assert phrase not in lowered, (
                    f"{path.name} contains the banned claim {phrase!r}. Overlapping "
                    f"marginal CIs are not a test of a difference, and failing to "
                    f"reject is not accepting the null."
                )

    def test_every_card_disclaims_production_and_advice(self):
        for path in [PRIMARY_CARD, *CHALLENGER_CARDS.values()]:
            card = _flat(path)
            assert "not** production-approved" in card
            assert "not** investment advice" in card

    def test_challenger_cards_say_they_are_not_the_reference(self):
        for path in CHALLENGER_CARDS.values():
            card = _flat(path)
            assert "did not establish statistically supported outperformance" in card
            assert "NOT the reference strategy" in card

    def test_challenger_cards_refuse_a_causal_reading(self):
        for path in CHALLENGER_CARDS.values():
            assert "Attribution is not causation" in _flat(path), (
                f"{path.name} must state that feature importance describes the "
                f"fitted function, not the market."
            )


class TestNoResultLiteralsInTheGenerator:
    """Same invariant as tests/test_run_dashboard_data.py, for the same reason."""

    def test_generator_hardcodes_no_sharpe_like_number(self):
        if not GENERATOR.is_file():
            pytest.skip("generator not present.")
        source = GENERATOR.read_text(encoding="utf-8")
        # Strip docstrings/comments: prose may legitimately mention "3.0-4.3%/yr".
        code = "\n".join(
            line.split("#")[0] for line in source.splitlines()
            if not line.strip().startswith("#")
        )
        code = re.sub(r'"""$.*?"""', "", code, flags=re.S | re.M)
        code = re.sub(r'f?"""(?:.|\n)*?"""', "", code)
        suspects = [
            literal for literal in re.findall(r"\b\d\.\d{3,}\b", code)
        ]
        assert not suspects, (
            f"The card generator contains result-shaped literals {suspects}. Every "
            f"number must be read from data/gold/ so a re-run cannot leave the "
            f"cards asserting a superseded figure."
        )


class TestWordDeliverablesCarryNoRetractedClaim:
    """The claim reframing must reach the binaries, not just the source tree.

    CLAUDE.md §17.11 is the record of a retracted claim surviving in six
    surfaces at once. The .docx deliverables are the surfaces a jury actually
    reads, and they are the ones a text search over the repository misses —
    `test_artifact_consistency.py` compares numbers, never wording, and nothing
    else looks inside a Word file. This closes that gap.

    Skips when python-docx or the files are absent, so a fresh clone stays
    green; asserts hard whenever they are present.
    """

    BANNED = (
        "statistiquement significatif",
        "statistiquement significative",
        "seul résultat significatif",
        "indiscernable",
        "indistinguable",
        "statistically significant",
        "statistically indistinguishable",
    )

    # Nothing is excluded. The annex was carved out while a teammate owned it;
    # it has since been corrected here, so the guard covers every Word
    # deliverable in docs/ without exception.
    NOT_OURS: set[str] = set()

    def test_no_word_deliverable_asserts_significance_or_equivalence(self):
        docx = pytest.importorskip("docx")
        paths = sorted((ROOT / "docs").glob("*.docx"))
        if not paths:
            pytest.skip("no Word deliverables present.")

        offenders = {}
        for path in paths:
            if path.name in self.NOT_OURS or path.name.startswith("~$"):
                continue  # ~$ files are Word lock files, not deliverables
            document = docx.Document(str(path))
            text = "\n".join(p.text for p in document.paragraphs)
            for table in document.tables:
                for row in table.rows:
                    text += "\n" + " | ".join(cell.text for cell in row.cells)
            lowered = text.lower()
            hits = [phrase for phrase in self.BANNED if phrase in lowered]
            if hits:
                offenders[path.name] = hits

        assert not offenders, (
            f"Word deliverable(s) still assert significance or equivalence: "
            f"{offenders}. Overlapping marginal intervals are not a test of a "
            f"difference in either direction — see docs/MODEL_GOVERNANCE.md and the "
            f"claim-reframing record. Fix the generator or the update script, then "
            f"regenerate; do not hand-edit the binary."
        )

    def test_evaluation_metrics_annex_documents_released_p4_protocol(self):
        """The jury-facing metrics annex must explain the tests it relies on."""
        docx = pytest.importorskip("docx")
        path = ROOT / "docs" / "Annexe_Metriques_Evaluation.docx"
        if not path.is_file():
            pytest.skip("evaluation-metrics annex not present.")
        document = docx.Document(str(path))
        text = "\n".join(p.text for p in document.paragraphs)
        for table in document.tables:
            for row in table.rows:
                text += "\n" + " | ".join(cell.text for cell in row.cells)
        required = (
            "4.3 Bootstrap pairé sur les différences",
            "4.4 Correction du choix parmi de nombreuses variantes",
            "White Reality Check et Hansen SPA",
            "regime_conditional",
            "equal_weight est exploratoire",
            "240 candidats",
        )
        missing = [phrase for phrase in required if phrase not in text]
        assert not missing, (
            "The evaluation-metrics annex no longer explains the released Phase 5 "
            f"comparison protocol: missing {missing}. Regenerate it with "
            "scripts/update_annexe_metriques.py rather than editing the binary."
        )
