"""
main.py — Thin FastAPI service over the portfolio system (Phase 6).

Addresses: P4 — a research-demo and anti-drift surface. The REST API serves
ONLY committed, DVC-tracked artifacts without importing the modelling code. It
is not an advisory, execution, or production investment service. Because it
never refits on request, what it returns is exactly what the pipeline produced
and can be re-derived from — the same reproducibility guarantee the dashboard's
integrity test enforces, extended to machine consumers. `/compare` ships the
uncertainty context inseparably with an observed difference.

Deliberately THIN. Every endpoint reads the committed Gold artifacts produced
by `src/run_dashboard_data.py`; none of them refit a model on request. That is
a design decision, not a limitation:

  * A walk-forward refit of `regime_conditional` takes ~4-13s per universe.
    Doing that inside a request handler would make the API unusable and would
    silently burn CPU on every page interaction.
  * The artifacts are DVC-tracked and regenerated by an explicit pipeline
    stage, so what the API serves is always reproducible and auditable — the
    same guarantee the dashboard's integrity test enforces.

Re-optimisation on demand (arbitrary as-of dates, custom constraints) is
explicitly out of scope for this pass and documented as such; it needs
data-refresh plumbing that belongs to a real deployment, not a local demo.

Run with:
    uvicorn api.main:app --reload --app-dir src
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query

from api.contracts import (
    ApiVersionResponse,
    ExplanationResponse,
    ModelCardResponse,
    PublishedAllocationResponse,
    SnapshotProvenance,
)

ROOT = Path(__file__).resolve().parents[2]
GOLD = ROOT / "data" / "gold"

app = FastAPI(
    title="Portfolio ML API",
    description=(
        "Interface REST de recherche pour l'optimisation de portefeuille "
        "(EURAFRIC / INPT). Sert les artefacts Gold versionnés produits par "
        "`src/run_dashboard_data.py`. Ni conseil d'investissement, ni exécution."
    ),
    version="1.1.0",
)


class ArtifactsMissing(HTTPException):
    def __init__(self, name: str) -> None:
        super().__init__(
            status_code=503,
            detail=(
                f"Artefact '{name}' introuvable. Lancez d'abord "
                f"`python src/run_dashboard_data.py` (ou `dvc repro dashboard_data`)."
            ),
        )


# Cache keyed on (path, mtime) rather than `lru_cache(maxsize=1)`.
#
# The plain version cached for the PROCESS LIFETIME: regenerate Gold and the API
# kept serving the previous numbers indefinitely, with no signal. That is the
# third instance of one bug class in this project — Dagster's gRPC code server
# served pre-`dividends.py` imports for days (§17.9), and Streamlit cached
# `shared.data` from before `load_crisis` existed. An API that silently serves
# superseded results is the worst of the three, because its consumers cannot
# see a stale timestamp the way a human reading a dashboard might.
#
# Keying on mtime means a regenerated artifact is picked up on the next request
# while repeat reads stay free.
@lru_cache(maxsize=8)
def _read_json(path_str: str, _mtime: float) -> dict:
    return json.loads(Path(path_str).read_text())


@lru_cache(maxsize=8)
def _read_parquet(path_str: str, _mtime: float) -> pd.DataFrame:
    return pd.read_parquet(path_str)


def _fresh(path: Path, required: bool = True):
    """Load `path`, re-reading whenever it changes on disk."""
    if not path.exists():
        if required:
            raise ArtifactsMissing(path.name)
        return None
    mtime = path.stat().st_mtime
    if path.suffix == ".json":
        return _read_json(str(path), mtime)
    return _read_parquet(str(path), mtime)


def _showcase() -> dict:
    return _fresh(GOLD / "dashboard_showcase.json")


def _equity() -> pd.DataFrame:
    return _fresh(GOLD / "dashboard_equity.parquet")


def _weights() -> pd.DataFrame:
    return _fresh(GOLD / "dashboard_weights.parquet")


def _crisis() -> dict | None:
    """Optional — absent artifact yields a 404 on /crisis, not a broken API."""
    return _fresh(GOLD / "crisis_windows.json", required=False)


def _explanations() -> dict:
    """Load the DVC-produced decision explanations; never reconstruct in-request."""
    return _fresh(GOLD / "model_explanations.json")


def _provenance() -> SnapshotProvenance:
    """Return the release identity without pretending an absent manifest is valid.

    Full checksum verification remains an explicit release gate
    (``python src/snapshot.py verify``).  The API exposes whether the manifest
    is available with every new contract response so a client cannot mistake a
    loose local artifact directory for a verified release.
    """
    manifest = _fresh(GOLD / "snapshot_manifest.json", required=False)
    if manifest is None:
        return SnapshotProvenance(
            status="unavailable",
            note=(
                "No snapshot manifest is available for this artifact directory. "
                "This response is suitable only for local research inspection."
            ),
        )
    # A manifest written from a dirty tree names a revision that does NOT
    # contain the code that produced these artifacts, which is why
    # `snapshot.py verify` rejects it outright. Reporting `producer_commit`
    # without that flag would hand a client a commit hash it cannot trust and
    # no way to tell — the same silent-staleness class this module's cache
    # comment already documents three instances of.
    dirty = bool(manifest.get("git_dirty"))
    return SnapshotProvenance(
        status="manifest_dirty_tree" if dirty else "manifest_present",
        manifest_path="data/gold/snapshot_manifest.json",
        producer_commit=manifest.get("git_commit"),
        producer_tree_dirty=dirty,
        generated_at_utc=manifest.get("generated_at_utc"),
        files_hashed=len(manifest.get("files", {})),
        note=(
            (
                "Manifest was generated from a DIRTY working tree, so producer_commit "
                "does not identify the code that produced these artifacts. "
                "`python src/snapshot.py verify` will reject this release."
            )
            if dirty
            else (
                "Manifest metadata is present. Verify the release checksums with "
                "`python src/snapshot.py verify` before relying on this artifact."
            )
        ),
    )


def _check_universe(universe: str) -> dict:
    universes = _showcase()["universes"]
    if universe not in universes:
        raise HTTPException(
            status_code=404,
            detail=f"Univers inconnu : '{universe}'. Disponibles : {sorted(universes)}.",
        )
    return universes[universe]


def _check_strategy(universe_data: dict, strategy: str) -> dict:
    strategies = universe_data["strategies"]
    if strategy not in strategies:
        raise HTTPException(
            status_code=404,
            detail=f"Stratégie inconnue : '{strategy}'. Disponibles : {sorted(strategies)}.",
        )
    return strategies[strategy]


@app.get("/health", tags=["meta"])
def health() -> dict:
    """Liveness + artifact-availability probe."""
    missing = [
        p.name for p in (
            GOLD / "dashboard_showcase.json",
            GOLD / "dashboard_equity.parquet",
            GOLD / "dashboard_weights.parquet",
        ) if not p.exists()
    ]
    return {"status": "ok" if not missing else "degraded", "missing_artifacts": missing}


@app.get("/version", response_model=ApiVersionResponse, tags=["meta"])
def version() -> ApiVersionResponse:
    """Service and release identity for machine consumers and audit logs."""
    return ApiVersionResponse(
        api_version=app.version,
        service_kind="read_only_research_artifact_api",
        research_only=True,
        order_execution_supported=False,
        provenance=_provenance(),
    )


@app.get("/strategies", tags=["catalogue"])
def list_strategies() -> dict:
    """Univers et stratégies disponibles, avec le contexte de backtest."""
    showcase = _showcase()
    return {
        "universes": {
            name: {
                "strategies": sorted(u["strategies"]),
                "oos_start": u["oos_start"],
                "oos_end": u["oos_end"],
                "assets": showcase["assets_per_universe"][name],
            }
            for name, u in showcase["universes"].items()
        },
        "backtest_context": {
            "rebalance_freq": showcase["rebalance_freq"],
            "max_weight": showcase["max_weight"],
            "cost_bps": showcase["cost_bps"],
        },
    }


@app.get("/metrics", tags=["résultats"])
def metrics(
    universe: str = Query(..., description="etf_2017 | full_2021"),
    strategy: str | None = Query(None, description="Omettre pour toutes les stratégies"),
) -> dict:
    """Métriques nettes de coûts, hors échantillon, pour un univers.

    Sans `strategy`, renvoie toutes les stratégies plus la comparaison
    ML vs. Markowitz classique de cet univers.
    """
    u = _check_universe(universe)
    if strategy is not None:
        return {
            "universe": universe,
            "strategy": strategy,
            "metrics": _check_strategy(u, strategy),
        }
    return {
        "universe": universe,
        "oos_start": u["oos_start"],
        "oos_end": u["oos_end"],
        "strategies": u["strategies"],
        "best_classical": u["best_classical"],
        "best_ml": u["best_ml"],
        "headline_lift_pct": u["headline_lift_pct"],
        # The out-of-sample interval is served alongside every headline, so a
        # consumer cannot quote the lift without also having its uncertainty.
        "phase5_test_window": u["phase5_test_window"],
    }


@app.get("/equity", tags=["résultats"])
def equity(
    universe: str = Query(...),
    strategy: str = Query(...),
    net: bool = Query(True, description="Net de coûts (True) ou brut (False)"),
) -> dict:
    """Courbe de valeur du portefeuille (base 100)."""
    u = _check_universe(universe)
    _check_strategy(u, strategy)

    df = _equity()
    rows = df[(df["universe"] == universe) & (df["strategy"] == strategy)].sort_values("Date")
    col = "net_return" if net else "gross_return"
    curve = (1.0 + rows[col]).cumprod() * 100.0
    return {
        "universe": universe,
        "strategy": strategy,
        "net": net,
        "dates": [d.strftime("%Y-%m-%d") for d in pd.DatetimeIndex(rows["Date"])],
        "values": [round(float(v), 4) for v in curve],
    }


@app.get("/weights", tags=["résultats"])
def weights(
    universe: str = Query(...),
    strategy: str = Query(...),
    latest_only: bool = Query(True, description="Dernière allocation seulement"),
) -> dict:
    """Allocations cibles — la dernière, ou l'historique complet des rééquilibrages."""
    u = _check_universe(universe)
    _check_strategy(u, strategy)

    df = _weights()
    rows = df[(df["universe"] == universe) & (df["strategy"] == strategy)]
    if rows.empty:
        raise HTTPException(status_code=404, detail="Aucune allocation trouvée.")

    if latest_only:
        last = rows["Date"].max()
        latest = rows[rows["Date"] == last].sort_values("weight", ascending=False)
        return {
            "universe": universe,
            "strategy": strategy,
            "as_of": last.strftime("%Y-%m-%d"),
            "weights": {r.asset: round(float(r.weight), 6) for r in latest.itertuples()},
        }

    history = {}
    for date, group in rows.groupby("Date"):
        history[date.strftime("%Y-%m-%d")] = {
            r.asset: round(float(r.weight), 6) for r in group.itertuples()
        }
    return {"universe": universe, "strategy": strategy, "history": history}


@app.get(
    "/published-allocation",
    response_model=PublishedAllocationResponse,
    tags=["publication"],
)
def published_allocation(
    universe: str = Query(..., description="etf_2017 | full_2021"),
    strategy: str = Query("regime_conditional"),
) -> PublishedAllocationResponse:
    """Typed contract for the latest published research allocation.

    This endpoint deliberately does not accept a custom date, capital amount,
    client profile, or market data.  It exposes an existing Gold artifact only.
    """
    u = _check_universe(universe)
    _check_strategy(u, strategy)
    df = _weights()
    rows = df[(df["universe"] == universe) & (df["strategy"] == strategy)]
    if rows.empty:
        raise HTTPException(status_code=404, detail="Aucune allocation publiée trouvée.")
    last = rows["Date"].max()
    latest = rows[rows["Date"] == last].sort_values("weight", ascending=False)
    return PublishedAllocationResponse(
        contract="published_research_allocation/v1",
        universe=universe,
        strategy=strategy,
        as_of=last.strftime("%Y-%m-%d"),
        weights={r.asset: round(float(r.weight), 6) for r in latest.itertuples()},
        research_only=True,
        order_execution_supported=False,
        provenance=_provenance(),
        caveat=(
            "Published historical research allocation only; not investment advice, "
            "not a client-specific recommendation, and not an order instruction."
        ),
    )


@app.get(
    "/explanations/{universe}",
    response_model=ExplanationResponse,
    tags=["publication"],
)
def explanation(universe: str) -> ExplanationResponse:
    """Return the versioned trace for the final published decision in a universe."""
    payload = _explanations()
    entry = payload.get("universes", {}).get(universe)
    if entry is None:
        available = sorted(payload.get("universes", {}))
        raise HTTPException(
            status_code=404,
            detail=f"Univers inconnu ou non expliqué : '{universe}'. Disponibles : {available}.",
        )
    return ExplanationResponse(
        contract="published_decision_explanation/v1",
        universe=universe,
        decision_date=entry["decision_date"],
        explanation=entry,
        provenance=_provenance(),
        caveat=(
            "Explanation describes a published final-rebalance research decision. "
            "Feature attribution is not causal and this endpoint never refits a model."
        ),
    )


_MODEL_CARDS = {
    "regime_conditional": "MODEL_CARD_REGIME_CONDITIONAL.md",
    "rf_challenger": "MODEL_CARD_RF_CHALLENGER.md",
    "xgb_challenger": "MODEL_CARD_XGB_CHALLENGER.md",
}


@app.get("/model-card/{system}", response_model=ModelCardResponse, tags=["publication"])
def model_card(system: str) -> ModelCardResponse:
    """Return the generated model card for the reference system or a challenger."""
    filename = _MODEL_CARDS.get(system)
    if filename is None:
        raise HTTPException(
            status_code=404,
            detail=f"Système inconnu : '{system}'. Disponibles : {sorted(_MODEL_CARDS)}.",
        )
    path = ROOT / "docs" / filename
    if not path.exists():
        raise ArtifactsMissing(filename)
    return ModelCardResponse(
        contract="model_card/v1",
        system=system,
        markdown=path.read_text(encoding="utf-8"),
        provenance=_provenance(),
    )


@app.get("/crisis", tags=["résultats"])
def crisis(universe: str = Query("etf_2017")) -> dict:
    """Comportement en crise + détection de régime non supervisée.

    Analyse exploratoire sur cinq fenêtres de crise externes. Le test des
    signes de l'artefact est fourni comme diagnostic, non comme preuve
    confirmatoire ou comme justification d'une décision d'investissement.
    """
    data = _crisis()
    if not data:
        raise HTTPException(
            status_code=404,
            detail=("Artefact 'crisis_windows.json' absent. Lancez "
                    "`python experiments/crisis_windows.py`."),
        )
    per_universe = data.get("universes", {})
    if universe not in per_universe:
        raise HTTPException(
            status_code=404,
            detail=f"Univers inconnu ou non couvert : '{universe}'. "
                   f"Disponibles : {sorted(per_universe)}.",
        )
    detection = (data.get("regime_detection") or {}).get(universe)
    return {
        "universe": universe,
        "methodology": data["methodology"],
        "windows": data["crises"],
        "per_crisis": per_universe[universe],
        "regime_detection": detection,
        "caveat": (
            "Analyse exploratoire : le gain en crise revient à la CONTRAINTE de "
            "portefeuille et au modèle de covariance (P1/P3), pas spécifiquement à "
            "la couche de régime ; sur plusieurs fenêtres les optimiseurs sont "
            "identiques. Cinq fenêtres et un état « baissier » défini par son "
            "rendement moyen faible ne permettent pas une conclusion confirmatoire. "
            "Cette analyse ne démontre pas qu'agir sur la détection améliore le "
            "rendement."
        ),
    }


@app.get("/compare", tags=["résultats"])
def compare(universe: str = Query(...)) -> dict:
    """Comparaison directe ML vs. Markowitz classique pour un univers.

    Renvoie toujours le contexte d'incertitude avec l'écart observé : un
    consommateur ne peut pas récupérer ce chiffre sans sa réserve.
    """
    u = _check_universe(universe)
    return {
        "universe": universe,
        "best_classical": u["best_classical"],
        "best_ml": u["best_ml"],
        "lift_pct": u["headline_lift_pct"],
        "lift_absolute_sharpe": u["headline_lift_absolute_sharpe"],
        "out_of_sample_test": u["phase5_test_window"],
        "caveat": (
            "L'écart est une estimation ponctuelle. Les intervalles à 90 % sont "
            "marginaux : ils quantifient l'incertitude mais ne constituent pas un "
            "test pairé de différence. Ne pas présenter comme une supériorité "
            "statistiquement démontrée."
        ),
    }
