"""
main.py — Thin FastAPI service over the portfolio system (Phase 6).

Addresses: the "production" deliverable — a REST surface a portfolio manager's
tooling (or the dashboard's manager page) can consume, rather than importing
the modelling code directly.

Deliberately THIN. Every endpoint reads the committed Gold artifacts produced
by `src/run_dashboard_data.py`; none of them refit a model on request. That is
a design decision, not a limitation:

  * A walk-forward refit of `regime_conditional` takes ~4-13s per universe.
    Doing that inside a request handler would make the API unusable and would
    silently burn CPU on every page interaction.
  * The artifacts are DVC-tracked and regenerated by an explicit pipeline
    stage, so what the API serves is always reproducible and auditable — the
    same guarantee the dashboard's integrity test enforces.

Re-optimisation on demand (arbitrary as-of dates, custom constraints) is
explicitly out of scope for this pass and documented as such; it needs
data-refresh plumbing that belongs to a real deployment, not a local demo.

Run with:
    uvicorn api.main:app --reload --app-dir src
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query

ROOT = Path(__file__).resolve().parents[2]
GOLD = ROOT / "data" / "gold"

app = FastAPI(
    title="Portfolio ML API",
    description=(
        "Interface REST du système d'optimisation de portefeuille "
        "(EURAFRIC / INPT). Sert les artefacts Gold versionnés produits par "
        "`src/run_dashboard_data.py`."
    ),
    version="1.0.0",
)


class ArtifactsMissing(HTTPException):
    def __init__(self, name: str) -> None:
        super().__init__(
            status_code=503,
            detail=(
                f"Artefact '{name}' introuvable. Lancez d'abord "
                f"`python src/run_dashboard_data.py` (ou `dvc repro dashboard_data`)."
            ),
        )


@lru_cache(maxsize=1)
def _showcase() -> dict:
    path = GOLD / "dashboard_showcase.json"
    if not path.exists():
        raise ArtifactsMissing(path.name)
    return json.loads(path.read_text())


@lru_cache(maxsize=1)
def _equity() -> pd.DataFrame:
    path = GOLD / "dashboard_equity.parquet"
    if not path.exists():
        raise ArtifactsMissing(path.name)
    return pd.read_parquet(path)


@lru_cache(maxsize=1)
def _weights() -> pd.DataFrame:
    path = GOLD / "dashboard_weights.parquet"
    if not path.exists():
        raise ArtifactsMissing(path.name)
    return pd.read_parquet(path)


def _check_universe(universe: str) -> dict:
    universes = _showcase()["universes"]
    if universe not in universes:
        raise HTTPException(
            status_code=404,
            detail=f"Univers inconnu : '{universe}'. Disponibles : {sorted(universes)}.",
        )
    return universes[universe]


def _check_strategy(universe_data: dict, strategy: str) -> dict:
    strategies = universe_data["strategies"]
    if strategy not in strategies:
        raise HTTPException(
            status_code=404,
            detail=f"Stratégie inconnue : '{strategy}'. Disponibles : {sorted(strategies)}.",
        )
    return strategies[strategy]


@app.get("/health", tags=["meta"])
def health() -> dict:
    """Liveness + artifact-availability probe."""
    missing = [
        p.name for p in (
            GOLD / "dashboard_showcase.json",
            GOLD / "dashboard_equity.parquet",
            GOLD / "dashboard_weights.parquet",
        ) if not p.exists()
    ]
    return {"status": "ok" if not missing else "degraded", "missing_artifacts": missing}


@app.get("/strategies", tags=["catalogue"])
def list_strategies() -> dict:
    """Univers et stratégies disponibles, avec le contexte de backtest."""
    showcase = _showcase()
    return {
        "universes": {
            name: {
                "strategies": sorted(u["strategies"]),
                "oos_start": u["oos_start"],
                "oos_end": u["oos_end"],
                "assets": showcase["assets_per_universe"][name],
            }
            for name, u in showcase["universes"].items()
        },
        "backtest_context": {
            "rebalance_freq": showcase["rebalance_freq"],
            "max_weight": showcase["max_weight"],
            "cost_bps": showcase["cost_bps"],
        },
    }


@app.get("/metrics", tags=["résultats"])
def metrics(
    universe: str = Query(..., description="etf_2017 | full_2021"),
    strategy: str | None = Query(None, description="Omettre pour toutes les stratégies"),
) -> dict:
    """Métriques nettes de coûts, hors échantillon, pour un univers.

    Sans `strategy`, renvoie toutes les stratégies plus la comparaison
    ML vs. Markowitz classique de cet univers.
    """
    u = _check_universe(universe)
    if strategy is not None:
        return {
            "universe": universe,
            "strategy": strategy,
            "metrics": _check_strategy(u, strategy),
        }
    return {
        "universe": universe,
        "oos_start": u["oos_start"],
        "oos_end": u["oos_end"],
        "strategies": u["strategies"],
        "best_classical": u["best_classical"],
        "best_ml": u["best_ml"],
        "headline_lift_pct": u["headline_lift_pct"],
        # The out-of-sample interval is served alongside every headline, so a
        # consumer cannot quote the lift without also having its uncertainty.
        "phase5_test_window": u["phase5_test_window"],
    }


@app.get("/equity", tags=["résultats"])
def equity(
    universe: str = Query(...),
    strategy: str = Query(...),
    net: bool = Query(True, description="Net de coûts (True) ou brut (False)"),
) -> dict:
    """Courbe de valeur du portefeuille (base 100)."""
    u = _check_universe(universe)
    _check_strategy(u, strategy)

    df = _equity()
    rows = df[(df["universe"] == universe) & (df["strategy"] == strategy)].sort_values("Date")
    col = "net_return" if net else "gross_return"
    curve = (1.0 + rows[col]).cumprod() * 100.0
    return {
        "universe": universe,
        "strategy": strategy,
        "net": net,
        "dates": [d.strftime("%Y-%m-%d") for d in pd.DatetimeIndex(rows["Date"])],
        "values": [round(float(v), 4) for v in curve],
    }


@app.get("/weights", tags=["résultats"])
def weights(
    universe: str = Query(...),
    strategy: str = Query(...),
    latest_only: bool = Query(True, description="Dernière allocation seulement"),
) -> dict:
    """Allocations cibles — la dernière, ou l'historique complet des rééquilibrages."""
    u = _check_universe(universe)
    _check_strategy(u, strategy)

    df = _weights()
    rows = df[(df["universe"] == universe) & (df["strategy"] == strategy)]
    if rows.empty:
        raise HTTPException(status_code=404, detail="Aucune allocation trouvée.")

    if latest_only:
        last = rows["Date"].max()
        latest = rows[rows["Date"] == last].sort_values("weight", ascending=False)
        return {
            "universe": universe,
            "strategy": strategy,
            "as_of": last.strftime("%Y-%m-%d"),
            "weights": {r.asset: round(float(r.weight), 6) for r in latest.itertuples()},
        }

    history = {}
    for date, group in rows.groupby("Date"):
        history[date.strftime("%Y-%m-%d")] = {
            r.asset: round(float(r.weight), 6) for r in group.itertuples()
        }
    return {"universe": universe, "strategy": strategy, "history": history}


@app.get("/compare", tags=["résultats"])
def compare(universe: str = Query(...)) -> dict:
    """Comparaison directe ML vs. Markowitz classique pour un univers.

    Renvoie toujours l'intervalle de confiance hors échantillon avec l'écart :
    un consommateur ne peut pas récupérer le gain sans son incertitude.
    """
    u = _check_universe(universe)
    return {
        "universe": universe,
        "best_classical": u["best_classical"],
        "best_ml": u["best_ml"],
        "lift_pct": u["headline_lift_pct"],
        "lift_absolute_sharpe": u["headline_lift_absolute_sharpe"],
        "out_of_sample_test": u["phase5_test_window"],
        "caveat": (
            "Le gain est une estimation ponctuelle ; les intervalles de confiance "
            "à 90 % sur la fenêtre de test gelée se chevauchent. Ne pas présenter "
            "comme une supériorité statistiquement démontrée."
        ),
    }
