"""
build_release_facts.py — write the canonical claims into the README and the report.

Addresses: P4 — the claims are GENERATED into both surfaces from
`src/release_facts.py` rather than typed into each, so
`tests/test_release_facts.py` can assert string equality instead of hunting for
approximately-similar numbers. A paraphrase is drift, and drift across surfaces
is a documented failure of this project (§17.11).

Both targets are written between explicit markers, so hand-written prose around
them survives regeneration.

Usage:
    python scripts/build_release_facts.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from release_facts import load_facts, statement_list  # noqa: E402

README = ROOT / "README.md"
# BOTH report trees input `chapters/faits_publies`. Writing only the first left
# `docs/rapport_final/` carrying an unmanaged copy that drifted out of sync —
# the same gap that let a hand-typed `0 fallback` survive there (CLAUDE.md
# §17.11). A generator that knows about one of two copies is not a generator.
TEX_PATHS = (
    ROOT / "docs" / "rapport" / "chapters" / "faits_publies.tex",
    ROOT / "docs" / "rapport_final" / "chapters" / "faits_publies.tex",
)

BEGIN = "<!-- BEGIN RELEASE FACTS — generated by scripts/build_release_facts.py -->"
END = "<!-- END RELEASE FACTS -->"


def _tex_escape(text: str) -> str:
    """Markdown emphasis and backticks -> LaTeX, then escape what remains.

    Deliberately small: the statements are generated, so the set of constructs
    that can appear here is known rather than arbitrary.
    """
    out = text.replace("\\", r"\textbackslash{}")
    for ch in ("&", "%", "$", "#", "_", "{", "}"):
        out = out.replace(ch, "\\" + ch)
    # **bold** -> \textbf{}, `code` -> \texttt{}
    while "**" in out:
        out = out.replace("**", r"\textbf{", 1).replace("**", "}", 1)
    while out.count("`") >= 2:
        out = out.replace("`", r"\texttt{", 1).replace("`", "}", 1)
    return out.replace("→", r"$\rightarrow$")


def build_readme_block(statements: list[str]) -> str:
    lines = [
        BEGIN,
        "",
        "### Faits publiés — ce que ce dépôt établit, et ce qu'il n'établit pas",
        "",
        "> Bloc généré depuis `src/release_facts.py`. Les mêmes phrases, mot pour mot,",
        "> figurent dans le rapport, le tableau de bord et l'API ; un test échoue si",
        "> une surface s'en écarte.",
        "",
    ]
    lines += [f"{i}. {s}" for i, s in enumerate(statements, 1)]
    lines += ["", END]
    return "\n".join(lines)


def build_tex(statements: list[str], facts: dict) -> str:
    body = "\n".join(f"  \\item {_tex_escape(s)}" for s in statements)
    return f"""% GENERATED by scripts/build_release_facts.py — do not edit by hand.
% The same sentences appear verbatim in README.md, the dashboard and the API;
% tests/test_release_facts.py fails if any surface diverges.
\\chapter*{{Faits publiés}}
\\addcontentsline{{toc}}{{chapter}}{{Faits publiés}}
\\markboth{{FAITS PUBLIÉS}}{{FAITS PUBLIÉS}}

Ce chapitre énonce, sans interprétation, ce que les résultats de ce dépôt
établissent et ce qu'ils n'établissent pas. Chaque énoncé est produit à partir
des artefacts Gold ; aucun nombre n'y est saisi à la main.

\\begin{{enumerate}}
{body}
\\end{{enumerate}}

\\medskip
\\noindent\\textbf{{Comparateur primaire.}} Le comparateur
\\texttt{{regime\\_conditional}} a été fixé \\emph{{avant}} l'observation des
résultats et sert de référence aux tests de White et de Hansen sur
{facts['multiple_testing']['n_candidates']} configurations. Il n'est ni un
système recommandé, ni un candidat déployé.
"""


def main() -> int:
    facts = load_facts(ROOT)
    statements = statement_list(ROOT)

    block = build_readme_block(statements)
    text = README.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    README.write_text(text, encoding="utf-8")

    tex = build_tex(statements, facts)
    written_tex: list[Path] = []
    for path in TEX_PATHS:
        # Skip a report tree that does not exist on this branch rather than
        # creating an orphan `chapters/` directory for a document that is not
        # here. Every tree that IS present must be written.
        if not path.parent.parent.is_dir():
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(tex, encoding="utf-8")
        written_tex.append(path)

    print(f"  {README.relative_to(ROOT)}  ({len(statements)} statements)")
    for path in written_tex:
        print(f"  {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
