<#
.SYNOPSIS
    Install dagster-daemon + dagster-webserver as Windows Scheduled Tasks.

.DESCRIPTION
    The Windows counterpart of scripts/setup_launchd.sh, which installs the same
    two processes as macOS LaunchAgents. It keeps the Phase 1 pipeline schedule
    running across logons without a terminal open. Run it again at any time to
    pick up a moved project path.

    WHY A WRAPPER .cmd IS GENERATED. A LaunchAgent plist carries an
    EnvironmentVariables dict; a Scheduled Task action does not. DAGSTER_HOME and
    FRED_API_KEY must both reach the daemon's spawned code-server subprocess, so
    the task launches a generated wrapper that sets them and then execs the
    dagster binary. The wrapper lives under .dagster_home\, which is gitignored,
    so the API key never lands anywhere tracked.

    WHY AtLogOn AND NOT AtStartup. The macOS agents are per-user LaunchAgents,
    not system-wide LaunchDaemons. Matching that keeps the daemon running as the
    developer, with the developer's profile and file permissions, rather than
    silently gaining SYSTEM privileges it has no use for.

.PARAMETER Uninstall
    Stop and remove both tasks. .dagster_home\ data is left untouched.

.EXAMPLE
    .\scripts\setup_dagster_tasks.ps1
    .\scripts\setup_dagster_tasks.ps1 -Uninstall
#>
[CmdletBinding()]
param([switch] $Uninstall)

$ErrorActionPreference = 'Stop'

$ProjectRoot  = Split-Path -Parent $PSScriptRoot
$VenvBin      = Join-Path $ProjectRoot '.venv\Scripts'
$DagsterHome  = Join-Path $ProjectRoot '.dagster_home'
$LogDir       = Join-Path $DagsterHome 'logs'

$DaemonTask    = 'PortfolioML-DagsterDaemon'
$WebserverTask = 'PortfolioML-DagsterWebserver'

function Remove-TaskIfPresent {
    param([string] $Name)
    $existing = Get-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
    if ($existing) {
        Stop-ScheduledTask -TaskName $Name -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $Name -Confirm:$false
    }
}

if ($Uninstall) {
    Write-Host "Stopping and removing Dagster scheduled tasks..."
    Remove-TaskIfPresent $DaemonTask
    Remove-TaskIfPresent $WebserverTask
    Write-Host "Done. (.dagster_home\ data was left untouched.)"
    exit 0
}

foreach ($exe in @('dagster-daemon.exe', 'dagster-webserver.exe')) {
    if (-not (Test-Path -LiteralPath (Join-Path $VenvBin $exe))) {
        Write-Error "$VenvBin\$exe not found -- run 'pip install -r requirements.txt' in .venv first."
    }
}

$EnvFile = Join-Path $ProjectRoot '.env'
if (-not (Test-Path -LiteralPath $EnvFile)) {
    Write-Error "$EnvFile not found -- create it with FRED_API_KEY=... first."
}

# Read the key directly rather than depending on dotenv auto-load propagating
# through the daemon's spawned subprocess -- the same reasoning as the macOS script.
$FredKey = (Select-String -LiteralPath $EnvFile -Pattern '^FRED_API_KEY=' |
            Select-Object -First 1).Line -replace '^FRED_API_KEY=', ''
if ([string]::IsNullOrWhiteSpace($FredKey)) {
    Write-Error "FRED_API_KEY not found in $EnvFile"
}

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# Telemetry off; everything else (run/event/schedule storage) defaults to local
# SQLite under DAGSTER_HOME, created automatically on first run.
Set-Content -LiteralPath (Join-Path $DagsterHome 'dagster.yaml') -Encoding utf8 -Value @"
telemetry:
  enabled: false
"@

function New-Wrapper {
    param([string] $FileName, [string] $Exe, [string] $Arguments, [string] $LogStem)
    $path = Join-Path $DagsterHome $FileName
    $body = @"
@echo off
REM Generated by scripts\setup_dagster_tasks.ps1 -- do not edit; re-run the script.
set "DAGSTER_HOME=$DagsterHome"
set "FRED_API_KEY=$FredKey"
cd /d "$ProjectRoot"
"$VenvBin\$Exe" $Arguments >> "$LogDir\$LogStem.log" 2>> "$LogDir\$LogStem.err.log"
"@
    Set-Content -LiteralPath $path -Encoding ascii -Value $body
    return $path
}

$daemonWrapper = New-Wrapper 'run-dagster-daemon.cmd' 'dagster-daemon.exe' `
                             'run -w workspace.yaml' 'dagster-daemon'
$webWrapper    = New-Wrapper 'run-dagster-webserver.cmd' 'dagster-webserver.exe' `
                             '-w workspace.yaml -h 127.0.0.1 -p 3000' 'dagster-webserver'

# KeepAlive equivalent: restart indefinitely on exit, one minute apart. Windows
# caps RestartCount, so 999 is the practical stand-in for launchd's KeepAlive.
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew

$trigger   = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

foreach ($pair in @(@{ Name = $DaemonTask; Script = $daemonWrapper },
                    @{ Name = $WebserverTask; Script = $webWrapper })) {
    Remove-TaskIfPresent $pair.Name
    $action = New-ScheduledTaskAction -Execute 'cmd.exe' `
                                      -Argument "/c `"$($pair.Script)`"" `
                                      -WorkingDirectory $ProjectRoot
    Register-ScheduledTask -TaskName $pair.Name -Action $action -Trigger $trigger `
                           -Settings $settings -Principal $principal | Out-Null
    Start-ScheduledTask -TaskName $pair.Name
}

Write-Host "Installed and started:"
Write-Host "  $DaemonTask"
Write-Host "  $WebserverTask"
Write-Host ""
Write-Host "UI:    http://127.0.0.1:3000"
Write-Host "Logs:  $LogDir\"
Write-Host "Status check:"
Write-Host "  Get-ScheduledTask -TaskName $DaemonTask | Get-ScheduledTaskInfo"
Write-Host "Uninstall:"
Write-Host "  .\scripts\setup_dagster_tasks.ps1 -Uninstall"
